### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by jaykumar16** [MRSRL/dl-cs#1]
I am running data_prep.py first to gather the data in my normal computer and I am getting MemorryError: unable to make matrix even tho I have 16GB RAM and GPU of 6GB.

I try this on the cluster and I am getting the following error:  

Traceback (most recent call last):
  File "data_prep.py", line 363, in <module>
    ismrmrd_to_npy(dir_mridata_org, dir_npy)
  File "data_prep.py", line 98, in ismrmrd_to_npy
    np.save(file_output, kspace.astype(np.complex64))
  File "/home/jaykumar/Envjay/lib/python3.6/site-packages/numpy/lib/npyio.py", line 536, in save
    pickle_kwargs=pickle_kwargs)
  File "/home/jaykumar/Envjay/lib/python3.6/site-packages/numpy/lib/format.py", line 640, in write_array
    array.tofile(fp)
OSError: problem writing element 524288 to file

**Comment by ekcole** [comment]
maybe this will help?
https://github.com/numpy/numpy/issues/5336
